### PR TITLE
Refactored almost according to agreed structure.

### PR DESCRIPTION
**Pull request by BogdanSorlea**
@Rasmuskrj @sjens 

This is my first stab at the structure. It is almost following what was committed yesterday from DTU, with some exceptions:
- decided not to add more objects than needed, so I've used the actual Client as the "blackboard" (blackboard still to be expanded as needed)
- given that there will be one planning per agent, I decided to use the Agent as a "Planner class" (i.e. give agent strategy and solution attributes - Agent already had the act( ) method, so it kind of indicated that the original intent might have been to use Agent as the object that keeps track of the plan, i.e. Planner)

Didn't manage to finish up testing this, as I have been running out of time (was tired yesterday, need to run to work now) - I think the idea is good (read this as "it would work using this approach"), but I am not completely sure it works.

I tried to implement the complete flow and at least I managed to do so without any IDE errors/warnings, so it's on the right track, I think (so feel free to branch off this branch for whatever changes - even merge to master, if it makes sense).

Will try to look at it some more tonight.

### CODE REVIEW

**Comment by BogdanSorlea** [comment]
@sjens @Rasmuskrj I am as we speak fixing out some exceptions around what I previously committed - it looks promising. I will hopefully make a new commit in 1-2 hours.

**Comment by Rasmuskrj** [comment]
Sounds very good! I tried pulling from structuring but I got a load of merge conflicts... Will try to pull again later and look at it all.

**Comment by BogdanSorlea** [comment]
@Rasmuskrj @sjens all I can say is

```
Bogdans-MacBook-Pro:02285YSoSirius bogdansorlea$ java -jar server.jar -l levels/Simple.lvl -c "java -classpath bin client.OneAgentClient"
<From Client> Hello from OneAgentClient. I am sending this using the error outputstream
Initial State
+++++++
+0 A  +
+++++++

<From Client>
+++++++
+ 0A  +
+++++++

<From Client> [true]
+++++++
+  0A +
+++++++

<From Client> [true]
+++++++
+   0A+
+++++++

success
<From Client> [true]
<Client IOException> Stream closed
```

will commit the latest changes in a sec

**Comment by BogdanSorlea** [comment]
So, the single agent setup seems to be working - tested on a simple setup (see above).

Command to test was `java -jar server.jar -l levels/Simple.lvl -c "java -classpath bin client.OneAgentClient"`

Some notes:
- I have created the Simple.lvl file to test this
- I have added support for offline debugging (i.e. running the Client without the need for a Server)

To enable offline debugging:
- read comment at https://github.com/Rasmuskrj/02285YSoSirius/blob/structuring/src/main/java/client/OneAgentClient.java#L13 (uncommenting this will allow offline (i.e. serverless) debugging with input coming from a file - to test just uncomment, add breakpoints to code and run the main class)
- read comment at https://github.com/Rasmuskrj/02285YSoSirius/blob/structuring/src/main/java/client/OneAgentClient.java#L30 (uncommenting this will print out the solution to sys err)

Have a look at it, and if ok we should probably merge it to master - so that future branching would go off master rather than this branch.

**Comment by Rasmuskrj** [comment]
Very nice job Bogdan. This leaves us on schedule :) I think that you should go ahead and merge that into master branch.

**Pull request merged**
