### PR TITLE
Refactored as to use the std. java src/bin struct.

### PR DESCRIPTION
**Pull request by BogdanSorlea**
Created the resources folder in root instead of src/main/resources, as it
would be harder to type in commands.

### CODE REVIEW

**Comment by BogdanSorlea** [comment]
Restructuring has been done in Eclipse (JEE). The restructuring should work in IntelliJ as well, it might require changing the source path to `src/main/java`. 

Please check the added information into `REAMDE.md` file, as it contains information on how to continue being compatible with the change (initial version - from environment.zip - would have had the same problem, I think).

The information added in the readme has been tested using at least one command given as example - and the output was the expected one, a ton of output of random agent movement on the level map.

**Comment by BogdanSorlea** [comment]
@sjens @Rasmuskrj PR ready for review. I will not merge it into master until I get a :+1: from each of you. Se previous comment as well (above on this thread).

**Comment by Rasmuskrj** [comment]
looking good :+1:

**Comment by sjens** [comment]
Yep, looks good.

**Pull request merged**
